apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: app
spec:
  git:
    push:
      # push directly to master without opening a PR
      branch: master
  update:
    path: ./deploy/dev
    strategy: Setters
