apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

images:
- name: hello
  newName: ghcr.io/timebertt/flux-promotion-example/app

replacements:
- source:
    kind: Deployment
    name: hello
    fieldPath: spec.template.spec.containers.[name=hello].image
  targets:
  - select:
      kind: Deployment
      name: hello
    fieldPaths:
    - spec.template.spec.containers.[name=hello].env.[name=APP_IMAGE].value
