---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app
spec:
  interval: 10m
  sourceRef:
    kind: OCIRepository
    name: app
  path: ./manifests
  targetNamespace: default
  prune: true
  wait: true
  timeout: 5m
