---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sync
  namespace: prod
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./deploy/prod
  prune: true
  wait: true
  timeout: 5m
