---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app
  namespace: test
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./deploy/test
  prune: true
  wait: true
  timeout: 5m
